trainer:
  logger: true
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: train_loss
        save_top_k: 3
        mode: min
    - class_path: checkpoint.code_snapshot.CodeSnapshot
      init_args:
        filetype:
          - .py
          - .yaml
          - .json
          - .csv
    # Debugging Callbacks
    # - class_path: verification.batch_norm.BatchNormVerificationCallback
    # - class_path: verification.batch_gradient.BatchGradientVerificationCallback
    # - class_path: pl_bolts.callbacks.TrainingDataMonitor
    #   init_args:
    #     log_every_n_steps: 1
    # - class_path: pl_bolts.callbacks.ModuleDataMonitor
    #   init_args:
    #     log_every_n_steps: 1
    #     submodules: true
  default_root_dir: /experiments/pase_eeg
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  num_processes: 1
  devices: 1
  gpus: true
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 300
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: null
  log_every_n_steps: 50
  accelerator: gpu
  strategy: dp
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  terminate_on_nan: null
