model:
  class_path: pase_eeg.lit_modules.simple_classifier_lit.EEGNetLit
  init_args:
    model: "eegnetv1"
    # channels_config: configs/eeg_recording_standard/international_10_20_22.py
    # emb_dim: 256
    # num_classes: 4
    learning_rate: 5e-2
    min_learning_rate: 1e-7
    decay_rate: 0.5
    # pretrained_backend_weights_path: '/experiments/pase_eeg/lightning_logs/version_8/checkpoints/epoch=155-step=49763.ckpt'
data:
  class_path: pase_eeg.lit_modules.simple_classifier_lit.EEGBCIIV2aDataLit
  init_args:
    data_path: /data/BCI_Competition_IV/
    channels_config: configs/eeg_recording_standard/international_10_20_22.py
    train_patients:
      [
        # 1,
        # 2,
        # 3,
        # 4,
        # 5,
        # 6,
        # 7,
        # 8,
      ]
    test_patients: [9]
    batch_size: 32
    leave_one_out: false
    transforms:
      - class_path: pase_eeg.data.transforms.ToTensor
        init_args:
          device: "cpu"
          #- class_path: pase_eeg.data.transforms.ZNorm
          #init_args:
          #stats: "./notebooks/bci_comp_iv2a_stats.pkl"
          #mode: "mean-std"
seed_everything: null
trainer:
  default_root_dir: /experiments/pase_eeg/test
  log_every_n_steps: 1
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: train_acc
        save_top_k: 1
        save_last: true
        mode: max
        save_weights_only: true
        every_n_epochs: 280
    - class_path: checkpoint.code_snapshot.CodeSnapshot
      init_args:
        filetype:
          - .py
          - .yaml
          - .json
          - .csv
    # Debugging Callbacks
    # - class_path: verification.batch_norm.BatchNormVerificationCallback
    # - class_path: verification.batch_gradient.BatchGradientVerificationCallback
    # - class_path: pl_bolts.callbacks.TrainingDataMonitor
    #   init_args:
    #     log_every_n_steps: 1
    # - class_path: pl_bolts.callbacks.ModuleDataMonitor
    #   init_args:
    #     log_every_n_steps: 1
    #     submodules: true
ckpt_path: null
